# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-11-15 16:20:10
"""
import sys, os, arcpy
import tempfile
from arcpy import env

def Process_Fire_Mosaic():  # Raster to vector of latest month fire scars

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Latest_raster_mosaic_of_fire_scars = arcpy.Raster("Y:\\rapidfire\\publishing\\mosaics\\cvmsre_qld_m202201202209_afma2.tif")
    QLD_S2_FIRE_SCARS_LUT = "Y:\\rapidfire\\publishing\\RSC_S2_FireScarmapping.gdb\\QLD_S2_FIRE_SCARS_LUT"
    FireScarMapping_gdb = "Y:\\rapidfire\\publishing\\FireScarMapping.gdb"

    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    Latest_Month = "Y:\\rapidfire\\publishing\\FireScarMapping.gdb\\LatestMonth"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=Latest_raster_mosaic_of_fire_scars, out_polygon_features=Latest_Month, simplify="NO_SIMPLIFY", raster_field="Value", create_multipart_features="SINGLE_OUTER_PART", max_vertices_per_feature=None)

    # Process: Dice (Dice) (management)
    LatestMonth_Dice200K = "D:\\RSC_DataPublishing\\RSC_DataPublishing.gdb\\LatestMonth_Dice200K"
    arcpy.management.Dice(in_features=Latest_Month, out_feature_class=LatestMonth_Dice200K, vertex_limit=200000)

    # Process: Add Join (Add Join) (management)
    LatestMonth_Dice200K_Layer = arcpy.management.AddJoin(in_layer_or_view=LatestMonth_Dice200K, in_field="GRIDCODE", join_table=QLD_S2_FIRE_SCARS_LUT, join_field="MONTH", join_type="KEEP_ALL", index_join_fields="NO_INDEX_JOIN_FIELDS")[0]

    # Process: Feature Class To Feature Class (Feature Class To Feature Class) (conversion)
    FireScars_monthly = arcpy.conversion.FeatureClassToFeatureClass(in_features=LatestMonth_Dice200K_Layer, out_path=FireScarMapping_gdb, out_name="FireScars_monthly", where_clause="", field_mapping="ID \"ID\" true true false 0 Long 0 0,First,#,LatestMonth_Dice200K_Layer,LatestMonth_Dice200K.ID,-1,-1;MONTH \"MONTH\" true true false 4 Long 0 0,First,#,LatestMonth_Dice200K_Layer,QLD_S2_FIRE_SCARS_LUT.MONTH,-1,-1;MONTH_DESC \"MONTH_DESC\" true true false 25 Text 0 0,First,#,LatestMonth_Dice200K_Layer,QLD_S2_FIRE_SCARS_LUT.MONTH_DESC,0,25", config_keyword="")[0]

if __name__ == '__main__':
    # Get the arguments from the command-line except the filename
    argv = sys.argv[1:]
     
    with arcpy.EnvManager(scratchWorkspace=r"D:\RSC_DataPublishing\RSC_DataPublishing.gdb", workspace=r"D:\RSC_DataPublishing\RSC_DataPublishing.gdb"):
        Process_Fire_Mosaic()
